window.BOOK_SITE_DATA = {
  "generatedAt": "2026-08-19T22:56:55+09:00",
  "note": "실제 판매부수는 공개되지 않아 YES24 판매지수와 알라딘 세일즈포인트를 표시합니다.",
  "genres": {
    "general": {
      "label": "종합도서",
      "description": "YES24 국내도서 일간 베스트와 알라딘 국내도서 주간 베스트의 공통 인기 도서",
      "books": [
        {
          "rank": 1,
          "title": "세네카, 오늘을 빼앗기고 있는 당신에게",
          "yesRank": 1,
          "aladinRank": 1,
          "averageRank": 1,
          "publicationDate": "2026년 07월",
          "authors": "루키우스 안나이우스 세네카, 하와이 대저택",
          "publisher": "논픽션",
          "yesSales": 483597,
          "aladinSales": 222875,
          "yesRating": 8.9,
          "aladinRating": 9.7,
          "averageRating": 9.3,
          "yesUrl": "https://www.yes24.com/product/goods/192474512",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=396404956"
        },
        {
          "rank": 2,
          "title": "오디세이아",
          "yesRank": 3,
          "aladinRank": 5,
          "averageRank": 4,
          "publicationDate": "2025년 04월",
          "authors": "호메로스, 페테르 파울 루벤스, 박문재",
          "publisher": "현대지성",
          "yesSales": 224808,
          "aladinSales": 70615,
          "yesRating": 9.7,
          "aladinRating": 9,
          "averageRating": 9.35,
          "yesUrl": "https://www.yes24.com/product/goods/145242086",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=362390080"
        },
        {
          "rank": 3,
          "title": "찌니주의보",
          "yesRank": 6,
          "aladinRank": 6,
          "averageRank": 6,
          "publicationDate": "2026년 08월",
          "authors": "정지아",
          "publisher": "창비",
          "yesSales": 35334,
          "aladinSales": 52660,
          "yesRating": 9.9,
          "aladinRating": 9.6,
          "averageRating": 9.75,
          "yesUrl": "https://www.yes24.com/product/goods/195026262",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=400137507"
        },
        {
          "rank": 4,
          "title": "싯다르타",
          "yesRank": 9,
          "aladinRank": 3,
          "averageRank": 6,
          "publicationDate": "2002년 01월",
          "authors": "헤르만 헤세, 박병덕",
          "publisher": "민음사",
          "yesSales": 354552,
          "aladinSales": 299823,
          "yesRating": 9.5,
          "aladinRating": 9.1,
          "averageRating": 9.3,
          "yesUrl": "https://www.yes24.com/product/goods/257435",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=329596"
        },
        {
          "rank": 5,
          "title": "그랬다고 적었다",
          "yesRank": 19,
          "aladinRank": 2,
          "averageRank": 10.5,
          "publicationDate": "2026년 08월",
          "authors": "김애란",
          "publisher": "문학동네",
          "yesSales": 56403,
          "aladinSales": 85340,
          "yesRating": 10,
          "aladinRating": 10,
          "averageRating": 10,
          "yesUrl": "https://www.yes24.com/product/goods/195042981",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=400193697"
        },
        {
          "rank": 6,
          "title": "오뒷세이아",
          "yesRank": 17,
          "aladinRank": 4,
          "averageRank": 10.5,
          "publicationDate": "2026년 08월",
          "authors": "호메로스, 김헌",
          "publisher": "을유문화사",
          "yesSales": 99036,
          "aladinSales": 78130,
          "yesRating": 9.8,
          "aladinRating": 9.7,
          "averageRating": 9.75,
          "yesUrl": "https://www.yes24.com/product/goods/194511329",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=399401298"
        },
        {
          "rank": 7,
          "title": "안녕, 피터팬",
          "yesRank": 13,
          "aladinRank": 9,
          "averageRank": 11,
          "publicationDate": "2026년 06월",
          "authors": "전경철",
          "publisher": "이야기장수",
          "yesSales": 120474,
          "aladinSales": 59570,
          "yesRating": 9.8,
          "aladinRating": 9.8,
          "averageRating": 9.8,
          "yesUrl": "https://www.yes24.com/product/goods/192491734",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=396458047"
        },
        {
          "rank": 8,
          "title": "수족관",
          "yesRank": 14,
          "aladinRank": 11,
          "averageRank": 12.5,
          "publicationDate": "2023년 12월",
          "authors": "유래혁",
          "publisher": "포스터샵",
          "yesSales": 180516,
          "aladinSales": 130978,
          "yesRating": 9.2,
          "aladinRating": 7,
          "averageRating": 8.1,
          "yesUrl": "https://www.yes24.com/product/goods/124235834",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=330811810"
        },
        {
          "rank": 9,
          "title": "투명한 나선",
          "yesRank": 22,
          "aladinRank": 8,
          "averageRank": 15,
          "publicationDate": "2026년 07월",
          "authors": "히가시노 게이고, 김선영",
          "publisher": "북다",
          "yesSales": 208668,
          "aladinSales": 124235,
          "yesRating": 9.8,
          "aladinRating": 9.9,
          "averageRating": 9.850000000000001,
          "yesUrl": "https://www.yes24.com/product/goods/193807963",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=398021172"
        },
        {
          "rank": 10,
          "title": "모순",
          "yesRank": 8,
          "aladinRank": 22,
          "averageRank": 15,
          "publicationDate": "2013년 04월",
          "authors": "양귀자",
          "publisher": "쓰다",
          "yesSales": 435846,
          "aladinSales": 285555,
          "yesRating": 9.6,
          "aladinRating": 9,
          "averageRating": 9.3,
          "yesUrl": "https://www.yes24.com/product/goods/8759796",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=25843736"
        },
        {
          "rank": 11,
          "title": "니체의 초월자",
          "yesRank": 10,
          "aladinRank": 29,
          "averageRank": 19.5,
          "publicationDate": "2025년 10월",
          "authors": "프리드리히 니체, 김철",
          "publisher": "히읏",
          "yesSales": 402027,
          "aladinSales": 109081,
          "yesRating": 9.8,
          "aladinRating": 9.4,
          "averageRating": 9.600000000000001,
          "yesUrl": "https://www.yes24.com/product/goods/161401496",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=375395519"
        },
        {
          "rank": 12,
          "title": "2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상",
          "yesRank": 16,
          "aladinRank": 38,
          "averageRank": 27,
          "publicationDate": "2025년 12월",
          "authors": "최태성",
          "publisher": "이투스북",
          "yesSales": 520632,
          "aladinSales": 140552,
          "yesRating": 9.9,
          "aladinRating": 7.3,
          "averageRating": 8.6,
          "yesUrl": "https://www.yes24.com/product/goods/167466420",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=378969369"
        },
        {
          "rank": 13,
          "title": "ETS 토익 정기시험 기출문제집 1000 Vol. 5 RC",
          "yesRank": 15,
          "aladinRank": 43,
          "averageRank": 29,
          "publicationDate": "2025년 12월",
          "authors": "ETS",
          "publisher": "YBM(와이비엠)",
          "yesSales": 356898,
          "aladinSales": 104817,
          "yesRating": 9.8,
          "aladinRating": 7.7,
          "averageRating": 8.75,
          "yesUrl": "https://www.yes24.com/product/goods/168776448",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=380347281"
        },
        {
          "rank": 14,
          "title": "ETS 토익 정기시험 기출문제집 1000 Vol. 5 LC",
          "yesRank": 21,
          "aladinRank": 48,
          "averageRank": 34.5,
          "publicationDate": "2025년 12월",
          "authors": "ETS",
          "publisher": "YBM(와이비엠)",
          "yesSales": 333066,
          "aladinSales": 97424,
          "yesRating": 9.9,
          "aladinRating": 7.3,
          "averageRating": 8.6,
          "yesUrl": "https://www.yes24.com/product/goods/168776455",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=380347074"
        },
        {
          "rank": 15,
          "title": "2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하",
          "yesRank": 23,
          "aladinRank": 49,
          "averageRank": 36,
          "publicationDate": "2025년 12월",
          "authors": "최태성",
          "publisher": "이투스북",
          "yesSales": 480273,
          "aladinSales": 131661,
          "yesRating": 9.9,
          "aladinRating": null,
          "averageRating": 9.9,
          "yesUrl": "https://www.yes24.com/product/goods/167466432",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=378969617"
        }
      ]
    },
    "poetry": {
      "label": "시",
      "description": "YES24 한국 시와 알라딘 시 분야의 공통 인기 도서 상위 10권",
      "books": [
        {
          "rank": 1,
          "title": "꽃을 보듯 너를 본다",
          "yesRank": 1,
          "aladinRank": 9,
          "averageRank": 5,
          "publicationDate": "2015년 06월",
          "authors": "나태주",
          "publisher": "지혜",
          "yesSales": 89469,
          "aladinSales": 71579,
          "yesRating": 9.5,
          "aladinRating": 8.9,
          "averageRating": 9.2,
          "yesUrl": "https://www.yes24.com/product/goods/24259730",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=62163905"
        },
        {
          "rank": 2,
          "title": "물빛인쇄소",
          "yesRank": 8,
          "aladinRank": 3,
          "averageRank": 5.5,
          "publicationDate": "2026년 07월",
          "authors": "함민복",
          "publisher": "창비",
          "yesSales": 6564,
          "aladinSales": 9290,
          "yesRating": null,
          "aladinRating": 10,
          "averageRating": 10,
          "yesUrl": "https://www.yes24.com/product/goods/194344031",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=399047729"
        },
        {
          "rank": 3,
          "title": "필사, 어른이 되는 시간",
          "yesRank": 3,
          "aladinRank": 10,
          "averageRank": 6.5,
          "publicationDate": "2025년 07월",
          "authors": "나태주, 보담",
          "publisher": "북로그컴퍼니",
          "yesSales": 90468,
          "aladinSales": 19915,
          "yesRating": 9.9,
          "aladinRating": 10,
          "averageRating": 9.95,
          "yesUrl": "https://www.yes24.com/product/goods/148702080",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=367487178"
        },
        {
          "rank": 4,
          "title": "단 한 줄만 내 마음에 새긴다고 해도",
          "yesRank": 4,
          "aladinRank": 16,
          "averageRank": 10,
          "publicationDate": "2025년 06월",
          "authors": "나민애",
          "publisher": "포레스트북스",
          "yesSales": 163623,
          "aladinSales": 43736,
          "yesRating": 9.8,
          "aladinRating": 9.9,
          "averageRating": 9.850000000000001,
          "yesUrl": "https://www.yes24.com/product/goods/147178677",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=365272060"
        },
        {
          "rank": 5,
          "title": "어깨에 머리를 기대던 시절",
          "yesRank": 22,
          "aladinRank": 7,
          "averageRank": 14.5,
          "publicationDate": "2026년 06월",
          "authors": "고명재",
          "publisher": "난다",
          "yesSales": 6939,
          "aladinSales": 15795,
          "yesRating": 10,
          "aladinRating": 10,
          "averageRating": 10,
          "yesUrl": "https://www.yes24.com/product/goods/191694860",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=395437265"
        },
        {
          "rank": 6,
          "title": "지금 알고 있는 걸 그때도 알았더라면",
          "yesRank": 9,
          "aladinRank": 20,
          "averageRank": 14.5,
          "publicationDate": "2014년 12월",
          "authors": "류시화",
          "publisher": "열림원",
          "yesSales": 20433,
          "aladinSales": 29051,
          "yesRating": 9.7,
          "aladinRating": 8.9,
          "averageRating": 9.3,
          "yesUrl": "https://www.yes24.com/product/goods/15816722",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=137447"
        },
        {
          "rank": 7,
          "title": "나는 오래된 거리처럼 너를 사랑하고",
          "yesRank": 10,
          "aladinRank": 22,
          "averageRank": 16,
          "publicationDate": "2022년 08월",
          "authors": "진은영",
          "publisher": "문학과지성사",
          "yesSales": 26589,
          "aladinSales": 21360,
          "yesRating": 9.7,
          "aladinRating": 9.3,
          "averageRating": 9.5,
          "yesUrl": "https://www.yes24.com/product/goods/112220926",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=300364309"
        },
        {
          "rank": 8,
          "title": "반려 별자리",
          "yesRank": 21,
          "aladinRank": 13,
          "averageRank": 17,
          "publicationDate": "2026년 07월",
          "authors": "정끝별",
          "publisher": "문학동네",
          "yesSales": 2673,
          "aladinSales": 5210,
          "yesRating": null,
          "aladinRating": null,
          "averageRating": null,
          "yesUrl": "https://www.yes24.com/product/goods/194511293",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=399414328"
        },
        {
          "rank": 9,
          "title": "캔버스에 유채",
          "yesRank": 30,
          "aladinRank": 5,
          "averageRank": 17.5,
          "publicationDate": "2026년 08월",
          "authors": "이기리",
          "publisher": "문학동네",
          "yesSales": 1056,
          "aladinSales": 2190,
          "yesRating": null,
          "aladinRating": null,
          "averageRating": null,
          "yesUrl": "https://www.yes24.com/product/goods/195073959",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=400207818"
        },
        {
          "rank": 10,
          "title": "러브 온 더 락",
          "yesRank": 17,
          "aladinRank": 19,
          "averageRank": 18,
          "publicationDate": "2026년 04월",
          "authors": "고선경",
          "publisher": "창비",
          "yesSales": 9390,
          "aladinSales": 13471,
          "yesRating": 9,
          "aladinRating": 8.8,
          "averageRating": 8.9,
          "yesUrl": "https://www.yes24.com/product/goods/186640434",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=390661137"
        }
      ]
    },
    "adultPicture": {
      "label": "어른그림책",
      "description": "YES24와 알라딘 100세 그림책 분야의 공통 인기 도서 상위 10권",
      "books": [
        {
          "rank": 1,
          "title": "100만 번 산 고양이",
          "yesRank": 3,
          "aladinRank": 4,
          "averageRank": 3.5,
          "publicationDate": "2002년 10월",
          "authors": "사노 요코",
          "publisher": "비룡소",
          "yesSales": 11838,
          "aladinSales": 23292,
          "yesRating": 9.4,
          "aladinRating": 9.3,
          "averageRating": 9.350000000000001,
          "yesUrl": "https://www.yes24.com/product/goods/310786",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=383699"
        },
        {
          "rank": 2,
          "title": "꽃에 미친 김 군",
          "yesRank": 15,
          "aladinRank": 10,
          "averageRank": 12.5,
          "publicationDate": "2025년 01월",
          "authors": "김동성",
          "publisher": "보림",
          "yesSales": 8892,
          "aladinSales": 13788,
          "yesRating": 9.9,
          "aladinRating": 9.6,
          "averageRating": 9.75,
          "yesUrl": "https://www.yes24.com/product/goods/140202390",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=356445986"
        },
        {
          "rank": 3,
          "title": "누구나 비밀은 있다",
          "yesRank": 12,
          "aladinRank": 22,
          "averageRank": 17,
          "publicationDate": "2025년 07월",
          "authors": "고혜진",
          "publisher": "달그림",
          "yesSales": 3000,
          "aladinSales": 1598,
          "yesRating": 10,
          "aladinRating": 10,
          "averageRating": 10,
          "yesUrl": "https://www.yes24.com/product/goods/148408900",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=367096624"
        },
        {
          "rank": 4,
          "title": "틈만 나면",
          "yesRank": 20,
          "aladinRank": 16,
          "averageRank": 18,
          "publicationDate": "2023년 04월",
          "authors": "이순옥",
          "publisher": "길벗어린이",
          "yesSales": 5433,
          "aladinSales": 5629,
          "yesRating": 9.8,
          "aladinRating": 9.8,
          "averageRating": 9.8,
          "yesUrl": "https://www.yes24.com/product/goods/118469379",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=315175500"
        },
        {
          "rank": 5,
          "title": "고양이들의 천국",
          "yesRank": 38,
          "aladinRank": 3,
          "averageRank": 20.5,
          "publicationDate": "2026년 07월",
          "authors": "에밀 졸라, 티모테 르 베엘, 윤진",
          "publisher": "웅진주니어",
          "yesSales": 264,
          "aladinSales": 2060,
          "yesRating": 10,
          "aladinRating": 10,
          "averageRating": 10,
          "yesUrl": "https://www.yes24.com/product/goods/193989222",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=398438470"
        },
        {
          "rank": 6,
          "title": "열두 달의 정원",
          "yesRank": 24,
          "aladinRank": 18,
          "averageRank": 21,
          "publicationDate": "2026년 04월",
          "authors": "백지혜",
          "publisher": "창비",
          "yesSales": 1554,
          "aladinSales": 4340,
          "yesRating": 10,
          "aladinRating": 10,
          "averageRating": 10,
          "yesUrl": "https://www.yes24.com/product/goods/188129823",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=391447394"
        },
        {
          "rank": 7,
          "title": "별의 아이",
          "yesRank": 40,
          "aladinRank": 6,
          "averageRank": 23,
          "publicationDate": "2026년 07월",
          "authors": "클레어 A. 니볼라, 이상희",
          "publisher": "대교",
          "yesSales": 792,
          "aladinSales": 7115,
          "yesRating": 10,
          "aladinRating": 9.9,
          "averageRating": 9.95,
          "yesUrl": "https://www.yes24.com/product/goods/193591916",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=396147425"
        },
        {
          "rank": 8,
          "title": "당신의 마음에 이름을 붙인다면",
          "yesRank": 29,
          "aladinRank": 17,
          "averageRank": 23,
          "publicationDate": "2022년 06월",
          "authors": "마리야 이바시키나, 김지은",
          "publisher": "책읽는곰",
          "yesSales": 5310,
          "aladinSales": 8753,
          "yesRating": 9.6,
          "aladinRating": 9.7,
          "averageRating": 9.649999999999999,
          "yesUrl": "https://www.yes24.com/product/goods/110007345",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=296113941"
        },
        {
          "rank": 9,
          "title": "코시롱 해녀 밥상",
          "yesRank": 43,
          "aladinRank": 7,
          "averageRank": 25,
          "publicationDate": "2026년 05월",
          "authors": "소윤경",
          "publisher": "웅진주니어",
          "yesSales": 1212,
          "aladinSales": 6510,
          "yesRating": 10,
          "aladinRating": 10,
          "averageRating": 10,
          "yesUrl": "https://www.yes24.com/product/goods/190213196",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=394017164"
        },
        {
          "rank": 10,
          "title": "세상에서 가장 멋진 새",
          "yesRank": 42,
          "aladinRank": 19,
          "averageRank": 30.5,
          "publicationDate": "2026년 06월",
          "authors": "김복희, 이명애",
          "publisher": "사계절",
          "yesSales": 798,
          "aladinSales": 2890,
          "yesRating": 10,
          "aladinRating": 10,
          "averageRating": 10,
          "yesUrl": "https://www.yes24.com/product/goods/192298833",
          "aladinUrl": "https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=396173568"
        }
      ]
    }
  }
};

